[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120"

[variables]
ENABLE_SCHEDULER = "true"
CACHE_DIRECTORY = "cache"
LOG_LEVEL = "INFO"
